services:
- docker

env:
  global:
  - PRESTOSQL_RELEASE=338

install:
- curl -LO https://github.com/IBM/presto-db2/releases/download/${PRESTOSQL_RELEASE}/presto-db2-${PRESTOSQL_RELEASE}.zip
- unzip presto-db2-${PRESTOSQL_RELEASE}.zip

before_script:
  curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64 &&
  chmod +x container-structure-test-linux-amd64 &&
  mkdir -p $HOME/bin &&
  export PATH=$PATH:$HOME/bin &&
  mv container-structure-test-linux-amd64 $HOME/bin/container-structure-test

script:
- docker build -t "shawnzhu/prestodb:$TRAVIS_BRANCH" .
- container-structure-test test --image shawnzhu/prestodb:$TRAVIS_BRANCH --config test_config.yaml
